name: Platform builds

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build apk --debug
        working-directory: example
